# Generated by Django 4.2.16 on 2024-10-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_produto_categoria_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Sanduiches', max_length=50, verbose_name='Categoria'),
        ),
    ]
