# Generated by Django 4.2.16 on 2024-10-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='app/media/produtos/placeholder.webp', null=True, upload_to='produtos/', verbose_name='Foto'),
        ),
    ]
